### ISSUE TITLE
CSS bug: Styling problem when using "note over" in simple mode

### ISSUE THREAD

**Issue by Redsandro** [bramp/js-sequence-diagrams#163]
The boxes are transparent, causing problems:

![image](https://cloud.githubusercontent.com/assets/1702193/18909672/d004b098-8574-11e6-92a6-6e65f4d1b7b8.png)

As seen on: Chrome 55.0.2859.0 dev (64-bit)

__Workaround__

Manually add:

```css
.sequence-diagram [stroke="#000000"], .flow-chart [stroke="#000000"] {
    fill: #fff;
}
```

---

Originally reported at https://github.com/benweet/stackedit/issues/1021 but noticed it was upstream.
